# Generated by Django 3.0.8 on 2020-08-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_question', '0003_auto_20200818_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
