# Generated by Django 3.0.8 on 2020-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_question', '0005_auto_20200818_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='smiles',
        ),
        migrations.AddField(
            model_name='answer',
            name='smiles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
